name: Package Application with PyInstaller for Windows
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
      - "b*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Download FFMPEG
        run: |
          curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          tar -xf ffmpeg.zip -C dependencies
          move dependencies\ffmpeg-master-latest-win64-gpl dependencies\ffmpeg
          rm ffmpeg.zip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Application with PyInstaller
        run: |
          pyinstaller GoExport.spec

      - name: Copy files to dist folder
        run: |
          copy readme.md dist\
          copy LICENSE dist\
          xcopy assets dist\assets /E /I /Q /Y

      - name: Upload debug build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: dist

      - name: Create ZIP of build
        run: |
          powershell Compress-Archive -Path dist\* -DestinationPath build.zip

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
          prerelease: ${{ startsWith(github.ref_name, 'b') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
